name: dart_style_clone
version: 0.2.0+1 #dev
author: Dart Team <misc@dartlang.org>
description: Opinionated, automatic Dart source code formatter.
homepage: https://github.com/dart-lang/dart_style
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  analyzer: '>=0.25.0 <0.27.0'
  args: '>=0.12.1 <0.14.0'
  path: '>=1.0.0 <2.0.0'
  source_span: '>=1.1.1 <2.0.0'
  runtime:
    path: ../../../vm_runtime
dev_dependencies:
  async: '>=1.0.0 <=1.2.0' # Temporary to avoid 1.3.0.
  browser: '>=0.10.0 <0.11.0'
  scheduled_test: '>=0.12.0 <0.13.0'
  test: '>=0.12.0 <0.13.0'
executables:
  dartfmt: format
  dartformat: format # Allow the old name for compatibility.
